return {
  'folke/which-key.nvim',
  opts_extend = { 'spec' },
  opts = {
    preset = 'modern',
    timeoutlen = 1500,
    show_help = true,
    win = { title = 'Горячие клавиши' },
    icons = {
      mappings = true,
      rules = {
        { pattern = '[Пп]оиск', icon = ' ', color = 'blue' },
        { pattern = '[Дд]иагностик', icon = ' ', color = 'red' },
        { pattern = '[Пп]ереключить', icon = ' ', color = 'yellow' },
        { pattern = '[Gg]it', icon = ' ', color = 'red' },
        { pattern = '[Зз]акрыть', icon = ' ', color = 'red' },
        { pattern = '[Сс]охранить', icon = ' ', color = 'green' },
        { pattern = '[Нн]овый', icon = ' ', color = 'green' },
        { pattern = '[Бб]уфер', icon = '󰈔 ', color = 'cyan' },
        { pattern = '[Тт]ерминал', icon = ' ', color = 'red' },
        { pattern = '[Пп]лаги', icon = ' ', color = 'cyan' },
        { pattern = '[Гг]лавно', icon = '󰮍 ', color = 'magenta' },
        { pattern = '[Мм]еню', icon = '󰮍 ', color = 'magenta' },
        { pattern = '[Оо]бновить', icon = ' ', color = 'blue' },
        { pattern = '[Пп]овторить', icon = ' ', color = 'blue' },
        { pattern = '[Фф]ормат', icon = '󰉺 ', color = 'blue' },
        { pattern = '[Кк]омментарий', icon = ' ', color = 'yellow' },
        { pattern = '[Оо]тменить', icon = '↩ ', color = 'red' },
        { pattern = '[Сс]бросить', icon = ' ', color = 'red' },
        { pattern = '[Дд]обавить', icon = ' ', color = 'green' },
        { pattern = '[Вв]ыделить', icon = '󰆢 ', color = 'yellow' },
        { pattern = '[Аа]втор', icon = ' ', color = 'magenta' },
        { pattern = '[Сс]равн', icon = '󰌝 ', color = 'cyan' },
        { pattern = '[Пп]росмотр', icon = ' ', color = 'blue' },
        { pattern = '[Пп]одсветк', icon = '󰸰 ', color = 'yellow' },
        { pattern = '[Ии]ндекс', icon = ' ', color = 'green' },
        { pattern = '[Сс]писок', icon = ' ', color = 'cyan' },
        { pattern = '[Сс]вернуть', icon = ' ', color = 'yellow' },
        { pattern = '[Рр]аскрыть', icon = ' ', color = 'green' },
        { pattern = '[Пп]ерейти', icon = '󰦋 ', color = 'blue' },
        { pattern = '[Нн]авигация', icon = '󰦋 ', color = 'blue' },
        { pattern = '[Сс]сылк', icon = '󰌹 ', color = 'blue' },
        { pattern = '[Рр]еализация', icon = '󰋷 ', color = 'green' },
        { pattern = '[Оо]пределение', icon = ' ', color = 'blue' },
        { pattern = '[Тт]ип', icon = '󰜫 ', color = 'cyan' },
        { pattern = '[Дд]окументация', icon = ' ', color = 'cyan' },
        { pattern = '[Пп]ереименовать', icon = '󰑕 ', color = 'yellow' },
        { pattern = '[Кк]од', icon = ' ', color = 'blue' },
        { pattern = '[Сс]имвол', icon = ' ', color = 'cyan' },
        { pattern = '[Пп]роек', icon = '󰱼 ', color = 'blue' },
        { pattern = '[Нн]едавн', icon = '󱦟 ', color = 'cyan' },
        { pattern = '[Сс]правка', icon = '󰋖 ', color = 'blue' },
        { pattern = '[Гг]орячие', icon = ' ', color = 'blue' },
      },
    },
    spec = {
      { '<leader>;', group = 'Хлебные крошки', icon = ' ' },
      { '<leader>f', group = 'Поиск' },
      { '<leader>x', group = 'Закрыть', icon = ' ' },
      { '<leader>T', group = 'Табы', icon = ' ' },
      { '<leader>w', group = 'Окна', icon = ' ' },
      { '<leader>t', group = 'Переключить' },
      { '<leader>g', group = 'Git', icon = ' ', mode = { 'n', 'v' } },
      { '<leader>gT', group = 'Git: Переключить', icon = ' ' },
      { '<leader>l', group = 'LSP', icon = '󰧑 ' },
      { '<leader>n', group = 'Создать', icon = '󰎔 ' },
      { '<leader>d', group = 'Диагностика' },
    },
  },
}
